#!perl
use Cassandane::Tiny;

sub test_put_get_duration ($self)
{
    my $CalDAV = $self->{caldav};

    my $CalendarId = $CalDAV->NewCalendar({name => 'tasks'});
    $self->assert_not_null($CalendarId);

    my $uuid = "a2f1e6b0-9c34-4f8e-b567-1a2b3c4d5e6f";
    my $href = "$CalendarId/$uuid.ics";
    my $card = <<EOF;
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Test//Test//EN
CALSCALE:GREGORIAN
BEGIN:VTODO
UID:$uuid
DTSTAMP:20250101T120000Z
SUMMARY:Task with duration
DTSTART:20250110T090000Z
DURATION:PT2H
STATUS:IN-PROCESS
SEQUENCE:0
END:VTODO
END:VCALENDAR
EOF

    xlog $self, "PUT a VTODO with DTSTART and DURATION (no DUE)";
    $CalDAV->Request('PUT', $href, $card, 'Content-Type' => 'text/calendar');

    xlog $self, "GET the VTODO and verify DURATION is preserved";
    my $response = $CalDAV->Request('GET', $href);
    my $ical = $response->{content};
    $self->assert_matches(qr/DTSTART:20250110T090000Z/, $ical);
    $self->assert_matches(qr/DURATION:PT2H/, $ical);
    $self->assert_matches(qr/SUMMARY:Task with duration/, $ical);
    # DUE should not appear since we used DURATION
    $self->assert_does_not_match(qr/^DUE:/m, $ical);
}
