#!perl
use Cassandane::Tiny;

sub test_put_changes_etag ($self)
{
    my $CalDAV = $self->{caldav};

    my $CalendarId = $CalDAV->NewCalendar({name => 'tasks'});
    $self->assert_not_null($CalendarId);

    my $uuid = "d4f3a8b2-1e56-4c7d-a890-5b6c7d8e9f0a";
    my $href = "$CalendarId/$uuid.ics";
    my $card = <<EOF;
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Test//Test//EN
CALSCALE:GREGORIAN
BEGIN:VTODO
UID:$uuid
DTSTAMP:20250101T120000Z
SUMMARY:Original summary
STATUS:NEEDS-ACTION
SEQUENCE:0
END:VTODO
END:VCALENDAR
EOF

    my %Headers = (
        'Content-Type' => 'text/calendar',
        'Authorization' => $CalDAV->auth_header(),
    );

    xlog $self, "PUT a VTODO and capture ETag";
    my $Response = $CalDAV->{ua}->request('PUT', $CalDAV->request_url($href), {
        content => $card,
        headers => \%Headers,
    });
    $self->assert_num_equals(201, $Response->{status});
    my $etag1 = $Response->{headers}{etag};
    $self->assert_not_null($etag1);

    xlog $self, "HEAD to confirm ETag is stable";
    $Response = $CalDAV->{ua}->request('HEAD', $CalDAV->request_url($href), {
        headers => \%Headers,
    });
    $self->assert_num_equals(200, $Response->{status});
    $self->assert_str_equals($etag1, $Response->{headers}{etag});

    xlog $self, "PUT updated VTODO with changed SUMMARY";
    $card =~ s/Original summary/Updated summary/s;
    $Response = $CalDAV->{ua}->request('PUT', $CalDAV->request_url($href), {
        content => $card,
        headers => \%Headers,
    });
    $self->assert_num_equals(204, $Response->{status});
    my $etag2 = $Response->{headers}{etag};
    $self->assert_not_null($etag2);

    xlog $self, "ETag must have changed";
    $self->assert_str_not_equals($etag1, $etag2);
}
