#!perl
use Cassandane::Tiny;

sub test_put_get_delete ($self)
{
    my $CalDAV = $self->{caldav};

    my $CalendarId = $CalDAV->NewCalendar({name => 'tasks'});
    $self->assert_not_null($CalendarId);

    my $uuid = "3b678201-e45c-4f4e-a7cf-deaf08b951a0";
    my $href = "$CalendarId/$uuid.ics";
    my $card = <<EOF;
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Test//Test//EN
CALSCALE:GREGORIAN
BEGIN:VTODO
UID:$uuid
DTSTAMP:20250101T120000Z
SUMMARY:Buy groceries
STATUS:NEEDS-ACTION
DUE:20250115T170000Z
PRIORITY:1
SEQUENCE:0
END:VTODO
END:VCALENDAR
EOF

    xlog $self, "PUT a VTODO";
    $CalDAV->Request('PUT', $href, $card, 'Content-Type' => 'text/calendar');

    xlog $self, "GET the VTODO back";
    my $response = $CalDAV->Request('GET', $href);
    my $ical = $response->{content};
    $self->assert_matches(qr/SUMMARY:Buy groceries/, $ical);
    $self->assert_matches(qr/STATUS:NEEDS-ACTION/, $ical);
    $self->assert_matches(qr/DUE:20250115T170000Z/, $ical);
    $self->assert_matches(qr/UID:$uuid/, $ical);
    $self->assert_matches(qr/BEGIN:VTODO/, $ical);

    xlog $self, "DELETE the VTODO";
    my %Headers = (
        'Authorization' => $CalDAV->auth_header(),
    );
    my $res = $CalDAV->{ua}->request('DELETE', $CalDAV->request_url($href), {
        headers => \%Headers,
    });
    $self->assert_num_equals(204, $res->{status});

    xlog $self, "GET should now return 404";
    $res = $CalDAV->{ua}->request('GET', $CalDAV->request_url($href), {
        headers => \%Headers,
    });
    $self->assert_num_equals(404, $res->{status});
}
