#!perl
use Cassandane::Tiny;

sub test_put_get_completed ($self)
{
    my $CalDAV = $self->{caldav};

    my $CalendarId = $CalDAV->NewCalendar({name => 'tasks'});
    $self->assert_not_null($CalendarId);

    my $uuid = "b3e2f7c1-8d45-4a6b-9012-3c4d5e6f7a8b";
    my $href = "$CalendarId/$uuid.ics";
    my $card = <<EOF;
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Test//Test//EN
CALSCALE:GREGORIAN
BEGIN:VTODO
UID:$uuid
DTSTAMP:20250101T120000Z
SUMMARY:A task
STATUS:NEEDS-ACTION
DUE:20250115T170000Z
SEQUENCE:0
END:VTODO
END:VCALENDAR
EOF

    xlog $self, "PUT a non-completed VTODO";
    $CalDAV->Request('PUT', $href, $card, 'Content-Type' => 'text/calendar');

    xlog $self, "GET and verify it is NEEDS-ACTION";
    my $response = $CalDAV->Request('GET', $href);
    my $ical = $response->{content};
    $self->assert_matches(qr/STATUS:NEEDS-ACTION/, $ical);
    $self->assert_does_not_match(qr/COMPLETED:/, $ical);

    xlog $self, "PUT updated VTODO marking it completed";
    my $updated = <<EOF;
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Test//Test//EN
CALSCALE:GREGORIAN
BEGIN:VTODO
UID:$uuid
DTSTAMP:20250102T120000Z
SUMMARY:A task
STATUS:COMPLETED
COMPLETED:20250102T120000Z
PERCENT-COMPLETE:100
DUE:20250115T170000Z
SEQUENCE:1
END:VTODO
END:VCALENDAR
EOF

    $CalDAV->Request('PUT', $href, $updated, 'Content-Type' => 'text/calendar');

    xlog $self, "GET and verify COMPLETED, STATUS, PERCENT-COMPLETE";
    $response = $CalDAV->Request('GET', $href);
    $ical = $response->{content};
    $self->assert_matches(qr/STATUS:COMPLETED/, $ical);
    $self->assert_matches(qr/COMPLETED:20250102T120000Z/, $ical);
    $self->assert_matches(qr/PERCENT-COMPLETE:100/, $ical);
    $self->assert_matches(qr/SUMMARY:A task/, $ical);
}
