#!perl
use Cassandane::Tiny;

sub test_task_query_basic
    :min_version_3_9
    ($self)
{
    my $jmap = $self->{jmap};

    my $res = $jmap->CallMethods([
        ['TaskList/get', {}, 'R0'],
    ]);
    my $calId = $res->[0][1]{list}[0]{id};

    xlog $self, "create multiple tasks";
    $res = $jmap->CallMethods([
        ['Task/set', { create => {
            "1" => {
                "\@type" => "Task",
                title => "Alpha task",
                taskListIds => { $calId => JSON::true },
                start => "2025-01-10T09:00:00",
                timeZone => "Etc/UTC",
            },
            "2" => {
                "\@type" => "Task",
                title => "Beta task",
                taskListIds => { $calId => JSON::true },
                start => "2025-01-20T09:00:00",
                timeZone => "Etc/UTC",
            },
        }}, "R1"],
    ]);
    my $taskId1 = $res->[0][1]{created}{"1"}{id};
    my $taskId2 = $res->[0][1]{created}{"2"}{id};
    $self->assert_not_null($taskId1);
    $self->assert_not_null($taskId2);

    xlog $self, "query all tasks";
    $res = $jmap->CallMethods([
        ['Task/query', {}, "R2"],
    ]);
    $self->assert_num_equals(2, scalar @{$res->[0][1]{ids}});
}
